### ISSUE TITLE
Code style + some questions

### ISSUE THREAD

**Issue by Krakean** [MiloszKrajewski/K4os.Compression.LZ4#1]
Hello
Just a few questions:
1) LZ4_64.cs:
>private static readonly uint[] DeBruijnBytePos

DeBruijn?

2) Can you please comment declarations of important functions? What they do, what params expect, what output/result is expected... current project haven't comments in code at all :-\

3) Also, can you please provide simple compression/decompression test/example? Which for example take a folder with files using specified path, compress them, measure comp speed, and decompress resulted archive to another folder, and also measure decomp speed

4) I would like to start use your library in my game engine project as comp lib for archive format to keep game assets. So curious, will current source code structure will change much, or it will stay mostly the same? Also, comp/decomp works fine in current library in-dev state? :)

Anyway, thanks for your fanstastic job on adapting LZ4 to .NET Core 2.0. Looking forward when project became mature enough :)

**Comment by MiloszKrajewski** [comment]
0. DeBruijn: https://en.wikipedia.org/wiki/Nicolaas_Govert_de_Bruijn
1. This is some magic math, which is beyond my comprehension, I just know it works. For example, see here: https://cstheory.stackexchange.com/questions/19524/using-the-de-bruijn-sequence-to-find-the-lceil-log-2-v-rceil-of-an-integer
2. This is first pass to check if it works at all, I'll be porting it again. For now, original variable and function names are preserved to make porting easier. All those ported function will stay hidden (private) and I'll provide more idiomatic C# interface (LZ4Codec).
3. SilesiaCorpusBlockTests works fine. Check examples.
4. Let's say LZ4Codec will look more os less the same. LZ_64, LZ_64_HC will be private so don't assume you will be able to use it directly.

**Comment by Krakean** [comment]
@MiloszKrajewski thanks for answers.
One more question: is possible to build it without Paket? Would like to avoid unnecessary dependencies

**Comment by MiloszKrajewski** [comment]
I don't understand. You don't have download anything, everything get downloaded automatically. The assembly itself does not have dependency on `paket` (whatever it might mean)

**Comment by Krakean** [comment]
@MiloszKrajewski 
See screenshot: https://i.imgur.com/cauzqyA.png
You see this selected file? You have to run it before you can compile project, otherwise .csproj's will not be loaded. But before this, you have to install standalone nuget.exe otherwise you will be able to download and install Paket.
Anyway, is this anyhow required to make k4os to work? 
Or I can just grab .cs files and it will work fine without Paket?
Also, is LZ4.dll that arrive in Tests is mandatory? Seems like its your old LZ4Net, right?

**Comment by MiloszKrajewski** [comment]
Ok, yes, thay do have dependency on nuget.exe so you will need to have it somewhere on your PATH. 
I'm not going to change my pipeline, but to be honest, you can make it work without paket and fake as main assembly does not have any dependencies (you would need to edit .csproj though).

To be clear: it is for developing it, not for using it later, it won't need anything.

And yes: I used LZ4Net to cross test: compress with one decompress with other, and then check if it worked. This codebase is quite bug prone (unsafe, pointer arithmetic) so this gives me some sense of security. You can't really debug if random byte around 2nd megabytes gets corrupted, right?

**Comment by Krakean** [comment]
@MiloszKrajewski thanks for answers, now it all clear to me :)
