### ISSUE TITLE
h264 nal unit invalid

### ISSUE THREAD

**Issue by xlievo** [MiloszKrajewski/K4os.Compression.LZ4#100]
Out of curiosity, I compressed the h264 lossy encoding unit, and the result was a small increase in the number of bytes, at all LZ4Level.
Does it not apply to recompression of h264 frames?
```C#
LZ4Codec.Encode...
```

**Comment by MiloszKrajewski** [comment]
Not sure if I understand your question about "Does it not apply to recompression of h264 frames?", but I think I can explain the "small increase in the number of bytes":

H.264 is already highly compressed. Your hopes that you could compress already highly compressed data further a little bit misplaced. In such case you would be able to compress already compress data until it reaches 0 bytes.
