### ISSUE TITLE
Unexpected EndOfStreamException during Stream decompression

### ISSUE THREAD

**Issue by MarcFletcher** [MiloszKrajewski/K4os.Compression.LZ4#102]
**Description**
I'm updating the LZ compression/decompression support in a networking library (https://github.com/MarcFletcher/NetworkComms.Net) to provide .net8 support. This is being implemented at:

Compress:
https://github.com/MarcFletcher/NetworkComms.Net/blob/980adf0f318225e012587abad9da9f15cc81d8a8/QuickLZCompressor/QuickLZ.cs#L223

Decompress:
https://github.com/MarcFletcher/NetworkComms.Net/blob/980adf0f318225e012587abad9da9f15cc81d8a8/QuickLZCompressor/QuickLZ.cs#L246

Whilst testing out your stream support I have run into the following exception on decompression:

> System.IO.EndOfStreamException
>   HResult=0x80070026
>   Message=Unexpected end of stream. Data might be corrupted.
>   Source=K4os.Compression.LZ4.Streams
>   StackTrace:
>    at K4os.Compression.LZ4.Streams.Internal.ReaderExtensions.TryReadBlock[TStreamReader,TStreamState](TStreamReader stream, TStreamState& state, Byte[] buffer, Int32 offset, Int32 count, Boolean optional)
>    at K4os.Compression.LZ4.Streams.Frames.LZ4FrameReader`2.ReadMeta(EmptyToken _, Int32 length, Boolean optional)
>    at K4os.Compression.LZ4.Streams.Frames.LZ4FrameReader`2.Peek4(EmptyToken token)
>    at K4os.Compression.LZ4.Streams.Frames.LZ4FrameReader`2.ReadBlock(EmptyToken token)
>    at K4os.Compression.LZ4.Streams.Frames.LZ4FrameReader`2.ReadManyBytes(EmptyToken token, Span`1 buffer, Boolean interactive)
>    at K4os.Compression.LZ4.Streams.Frames.LZ4FrameReader`2.ReadManyBytes(Span`1 buffer, Boolean interactive)
>    at K4os.Compression.LZ4.Streams.LZ4DecoderStream.Read(Byte[] buffer, Int32 offset, Int32 count)
>    at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
>    at Examples.ExamplesConsole.Program.Main(String[] args) in C:\Users\MarcF\Documents\Coding\networkcomms\Platforms\Net80\ExamplesConsole\Program.cs:line 51

I'm expecting I've misunderstood something about the correct process here but if you could advise that would be greatly appreciated.

**To reproduce**
The following snippet demonstrates the same behaviour:
```
//Define input
byte[] orig = new byte[] { 10, 5, 104, 101, 108, 108, 111, 10, 5, 119, 111, 114, 108, 100 };

Stream input = new MemoryStream(orig);
Stream output = new MemoryStream();
LZ4EncoderStream lZ4EncoderStream = LZ4Stream.Encode(output);
input.CopyTo(lZ4EncoderStream);

//At this point NetworkComms.Net will transmit the compressed 7 byte buffer across the network

////////////////////////////////////////////////
///IGNORE THIS SECTION WHICH IS EQUIVALENT TO THE NETWORK PORTION
byte[] receivedBytes = new byte[output.Length];
output.Seek(0, SeekOrigin.Begin);
output.Read(receivedBytes, 0, receivedBytes.Length);
////////////////////////////////////////////////

//7 bytes are received
Stream receivedRaw = new MemoryStream(receivedBytes);
Stream receivedDecompressed = new MemoryStream();
LZ4DecoderStream lZ4DecoderStream = LZ4Stream.Decode(receivedRaw);

//Expecting to return to the original 14 byte decompressed array here
//Instead it results in an EndOfStreamException
lZ4DecoderStream.CopyTo(receivedDecompressed);
```

**Expected behavior**
receivedDecompressed contains the 14 byte values from orig. The absolute size of the receivedDecompressed memory stream buffer wouldn't matter.

**Actual behavior**
System.IO.EndOfStreamException: 'Unexpected end of stream. Data might be corrupted.'

**Environment**
 - CPU: Intel
 - OS: Windows
 - .NET: 8.0
 - LZ4: nuget 1.3.8

**Additional context**
I'm aware of your Pickler implementation for small frames which is very cool but I need to ensure the compression follows the expected standard for backwards compatibility.

**Comment by MiloszKrajewski** [comment]
This 7 bytes you think is your compressed data is just a header. The compressed data is not there until you actually close the frame. It is written in block (64k is default but can be changed) and you data is much less. So you need to tell stream: "there will be no more data, it is safe to close the frame".

```csharp
//Define input
byte[] orig = new byte[] { 10, 5, 104, 101, 108, 108, 111, 10, 5, 119, 111, 114, 108, 100 };

var input = new MemoryStream(orig);
var output = new MemoryStream();
var lZ4EncoderStream = LZ4Stream.Encode(output);
input.CopyTo(lZ4EncoderStream);

lZ4EncoderStream.Close(); // <-- YOU NEED TO CLOSE STREAM TO FLUSH LAST BLOCK

//At this point NetworkComms.Net will transmit the compressed 7 byte buffer across the network

////////////////////////////////////////////////
///IGNORE THIS SECTION WHICH IS EQUIVALENT TO THE NETWORK PORTION
var receivedBytes = output.ToArray(); // <-- MEMORY STREAM ALREADY HAS METHD TO THIS
////////////////////////////////////////////////

//7 bytes are received
Stream receivedRaw = new MemoryStream(receivedBytes);
Stream receivedDecompressed = new MemoryStream();
LZ4DecoderStream lZ4DecoderStream = LZ4Stream.Decode(receivedRaw);

//Expecting to return to the original 14 byte decompressed array here
//Instead it results in an EndOfStreamException
lZ4DecoderStream.CopyTo(receivedDecompressed);

Console.WriteLine(receivedDecompressed.Length);
```

**Comment by MarcFletcher** [comment]
Many thanks for the quick reply. 

Calling `lZ4EncoderStream.Close();` appears to close the underlying `output` stream. Unfortunately I need to leave the output stream open for further operations, and I can't assume it is a `MemoryStream` as you have done in your example.

I then hoped that `lZ4EncoderStream.Flush();` would write the last block but leave the underlying stream open, but unfortunately this doesn't appear to act in this way.

Can you please advise if there is another way to ensure the final block is written to the `output` stream without disposing of it?

**Comment by MiloszKrajewski** [comment]
> "leave the output stream open"

There is an parameter called... "leaveOpen"

> "I [...] hoped that Flush [...]"

That was a design decision. `Flush` for streams means "flush buffers, but I may be writing more", while in LZ4 world it would HAVE TO mean "flush buffers, and no further writes can be done" (it writes an end-of-stream marker).
So I decided it safer not adding such logic to `Flush` (imagine how many people would write a ticket saying: after I flushed my stream it unexpectedly truncated).

...but I assure you combination of `leaveOpen` and `Close` with works as you described.

**Comment by MarcFletcher** [comment]
Thanks for elaborating. Using the `leaveOpen` flag works as expected.

My tests are now passing and I look forward to including this support in our next release. If I run into any other issues I'll give you a shout.

Many thanks for your library.
