### ISSUE TITLE
[Question] Is this library thread safe?

### ISSUE THREAD

**Issue by LyingDwarf** [MiloszKrajewski/K4os.Compression.LZ4#11]
Are the static classes LZ4Codec, LZ4Pickler, etc safe to use from multiple threads concurrently?

What about the instance classes LZ4EncoderStream, LZ4DecoderStream, etc? (I would assume not)

**Comment by MiloszKrajewski** [comment]
All static method (mostly factories) are safe.
Instance methods on streams are not. I could put locks in them, but streams are not thread safe in most cases almost by definition (you know: "stream").
I guess you could have ThreadSafeStream decorator if you want to write from different threads to the safe stream.

**Comment by LyingDwarf** [comment]
Thank you for the answer. Your design is as I'd hoped and I agree that adding locks wouldn't really help for most streaming classes.
