### ISSUE TITLE
unable to decompress data received in API

### ISSUE THREAD

**Issue by vikasNew** [MiloszKrajewski/K4os.Compression.LZ4#17]
Hi i am getting lz4 compressed data in API request body. data is compressed in ios but when i try to decompress that data i get the following error.. "inputBuffer size is invalid or has been corrupted"

i am using the fokkowing metho to decompress data..

 var lorems =   Encoding.UTF8.GetString(LZ4Codec.Unwrap(Convert.FromBase64String(compressed)));

it works when i compress data with LZ4Codec.Wrap & decompress with Unwrap. but when it comes frm other plateforms(ios & andriod) then i got that issue..

please help me what i am missing here...

Thanks in anticipation

**Comment by MiloszKrajewski** [comment]
* There are no `Wrap`/`Unwrap` functions so I guess you created this ticket against wrong library
* LZ4 is very flexible algorithm and has two modes BLOCK and STREAM. I can ONLY guess that iOS data you receive is in STREAM mode, therefore you should use `LZ4Stream.Decode(...)`
