### ISSUE TITLE
Switch to Span<T>

### ISSUE THREAD

**Issue by epsitec** [MiloszKrajewski/K4os.Compression.LZ4#2]
Since you are reimplementing your library for .NET Standard 2, why not use `Span<T>` which brings huge performance improvements without having to use unsafe code and pointers?

See https://msdn.microsoft.com/en-us/magazine/mt814808.aspx for a great introductory article from Stephen Toub.

**Comment by MiloszKrajewski** [comment]
There is a plan to to it, but so far it is imperant to use `byte *` which is even more generic than `Span<byte>`. Once I have it working with `byte *` `Span<byte>` won't be a problem.

**Comment by MiloszKrajewski** [comment]
I read a little bit and apparently `Span<>` is stack-only. So it is not really a viable solution.

**Comment by MiloszKrajewski** [comment]
I read a little bit more and I have to admit I was wrong, so current status is: maybe.

**Comment by kraptor23** [comment]
Span just allows you to achieve some of the performance of pointers in a safe manner - I'd skip it as you are looking to port as mechanically as possible the pointer math etc from the C++ code. Looking forward to the first beta version - let us know when you are looking for some help testing things out!
