### ISSUE TITLE
Exception: Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by Krakean** [MiloszKrajewski/K4os.Compression.LZ4#21]
@MiloszKrajewski 
Here is picture with callstack: https://i.imgur.com/5J7R4H1.png
Exception happens only when arithmetic overflow checking is enabled in project settings (which is enabled in my case when I build Debug configuration).

**Comment by MiloszKrajewski** [comment]
Calculating a hash is absolutely expected to "wrap around" causing arithmetic overflow exception. What is not expected turning arithmetic overflow checking on. Who does that? :-)
Adding unchecked to explicitly turn it off will help.

**Comment by Krakean** [comment]
@MiloszKrajewski 
>What is not expected turning arithmetic overflow checking on. Who does that? :-)

Is it so useless option to enable? :-\

**Comment by MiloszKrajewski** [comment]
Definitely not in library which uses bit twiddling hacks, but... to avoid this problem I've wrapped has calculation in `unchecked`

**Comment by Krakean** [comment]
@MiloszKrajewski 
Another one happens in LZ4_64.cs here:
		protected static uint LZ4_NbCommonBytes(ulong val) =>
			DeBruijnBytePos[(ulong) ((long) val & -(long) val) * 0x0218A392CDABBD3Ful >> 58];

**Comment by MiloszKrajewski** [comment]
fixed in 1.1.10
