### ISSUE TITLE
Frame decompression with LZ4Stream.Decode seems to ignore all blocks after the first one

### ISSUE THREAD

**Issue by andrewsil1** [MiloszKrajewski/K4os.Compression.LZ4#23]
Please see discussion of this [issue.](https://github.com/lz4/lz4/issues/729)

To summarize: I have an incoming stream which is compressed with LZ4F_compressBegin/Update/End in a C program running on a Xilinx FPGA (Microblaze processor.) Options for the frame are set to use the 4MB block size, but can be reproduced with any block size.  

The problem is that when the size of the entire uncompressed buffer exceeds the block size (even if broken up into multiple calls to LZ4F_compressUpdate), then when the frame is decompressed in C#, the decompressed data in the stream ends after the block size is reached (1MB, 4MB, or whatever.)

Code performing the decompression:
``` 
using (var source = LZ4Stream.Decode(incomingData, 0, false))
{
    source.Read(drawBuffer, 0, ImageBufferLength);
}
```
ImageBufferLength is the full size in bytes required for the decompressed data (height*width*sizeof(short)) since in this case each data element is 2 bytes, and drawBuffer is more than large enough to hold it.

If I write the compressed data out to a file and decompress it with the LZ4 command line utility, I am able to verify that ALL of the data is decompressed from the frame into the resulting file and matches the original source buffer on the FPGA.  

I'm attaching a binary file containing the sample compressed frame as received by the C# app prior to decompression.
[compressedFrac.zip](https://github.com/MiloszKrajewski/K4os.Compression.LZ4/files/3277873/compressedFrac.zip)

At this point I can only assume that the stream API is somehow ignoring the data in the frame that exceeds the specified block length.

Your help would be greatly appreciated-

Thanks,
Andy

**Comment by MiloszKrajewski** [comment]
It is not obvious, but this stream uses "interactive" reading. 

If you look at [documentation for Stream.Read](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=netframework-4.8) you will find that it may read less than requested: "Returns: The total number of bytes read into the buffer. This can be less than the number of bytes requested if that many bytes are not currently available, or zero (0) if the end of the stream has been reached."

LZ4InputStream tries to return to you as quickly as possible and not block. In practice, it means that is will return some data on block boundary, and you need another read to read the rest.

**If you don't want to handle it yourself, you can use this helper method:**

```c#
public int FullBlockRead(Stream stream, byte[] buffer, int offset, int length)
{
	var total = 0;
	while (length > 0)
	{
		var read = stream.Read(buffer, offset, length);
		if (read == 0) return total;

		offset += read;
		length -= read;
		total += read;
	}
}
```

**Comment by andrewsil1** [comment]
Thank you for the clarification- it wasn’t obvious, you’re right. I’ll give that a try and report back.

Thanks-

**Comment by andrewsil1** [comment]
That does indeed cure it.  Thank you so much for the tip, it was driving me crazy. :-)
