### ISSUE TITLE
Can support net45?

### ISSUE THREAD

**Issue by realivanjx** [MiloszKrajewski/K4os.Compression.LZ4#26]
I already have an app that runs on net45 and my client wont upgrade to net46. Can you support net45? 

Thanks.

**Comment by MiloszKrajewski** [comment]
In general can be done as sources themselves do nt use any .NET 4.6 features, but I had problems with compatibility of dependencies: System.Memory and System.Buffers. There are some weird compilation errors when net 4.5 is added to the mix.

At the same time I remember having barriers like this NET 3.5 compatibility as it was used by Unity, NET 4.0 compatibility as this is last version supported by Windows XP. But .NET 4.5? Why it is a problem to upgrade?

**Comment by realivanjx** [comment]
We have hundreds of users already. Impossible to tell them one by one. My boss wouldnt like it either. What errors?

**Comment by realivanjx** [comment]
Net46 is also only preinstalled only with windows 10...

**Comment by MiloszKrajewski** [comment]
Don't quote me on that, but:

I don't remember exactly, but it was something about using `System.Runtime.CompilerServices.Unsafe` (transient dependency of System.Memory?) which, when .NET 4.5 was added to the mix, was forced to use some version, which was causing run-time exceptions on .NET 4.6 (it was compiling just fine, it just didn't work).

I'll take another look.

**Comment by MiloszKrajewski** [comment]
`Buffer.MemoryCopy` was the problem. You can try now. `1.1.11`
