### ISSUE TITLE
Problem decoding data

### ISSUE THREAD

**Issue by Jacobh2** [MiloszKrajewski/K4os.Compression.LZ4#27]
Hi!

I'm trying to decode a message which I have encoded in python using `py-lz4framed`, but having some issues.

Have I understood it correctly that I cannot use the `K4os.Compression.LZ4` package, since that says "Block compression only", and the `py-lz4framed` lib uses frames? This leaves me with the `K4os.Compression.LZ4.Streams` package.

My encoded message is not a stream, so what I've done is to use `MemoryStream` like this in order to get a stream:
```C#
Stream incomingStream = new MemoryStream(Encoding.UTF8.GetBytes(compressedStringMessage));
```

But I honestly don't understand how to continue to decode the message, I feel like I am misunderstanding something very basic here.

What I've got is:
```C#
byte[] source = Encoding.UTF8.GetBytes(compressedStringMessage)
MemoryStream incomingStream = new MemoryStream(source);
MemoryStream outgoingStream = new MemoryStream(source.Length * 255);
using (LZ4DecoderStream decodeSource = LZ4Stream.Decode(incomingStream, 0, false))
{
    decodeSource.CopyTo(outgoingStream);
}
```
which, depending on what I give it as `compressedStringMessage`, will either give me a
`System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection`
or an
`System.InvalidOperationException: Operation is not valid due to the current state of the object`.

Any pointers are very welcome 😅

**Comment by Jacobh2** [comment]
I compress the message in Python using [py-lz4framed](https://github.com/Iotic-Labs/py-lz4framed).

**Comment by MiloszKrajewski** [comment]
Can you attach some sample data?

**Comment by Jacobh2** [comment]
Sure thing! So in Python I do: (using version 0.13.0 of `py-lz4framed`)
```py
>>> encoded_string = "hello".encode()
>>> compressed_string = lz4framed.compress(encoded_string)
>>> print(compressed_string)
b'\x04"M\x18h@\x05\x00\x00\x00\x00\x00\x00\x00a\x05\x00\x00\x80hello\x00\x00\x00\x00'
```

I then send this over to the C# project using kafka. I have confirmed that I get the exact same bytes back: Both python and c# print the byte array: `[4, 34, 77, 24, 104, 64, 5, 0, 0, 0, 0, 0, 0, 0, 97, 5, 0, 0, 128, 104, 101, 108, 108, 111, 0, 0, 0, 0]`

One thing I noticed after posting here, is that using `Encoding.UTF8.GetBytes` gave me 2 extra bytes, so I changed it to `Encoding.ASCII.GetBytes`.

Here would be a minimal test:
```C#
byte[] input = { 4, 34, 77, 24, 104, 64, 5, 0, 0, 0, 0, 0, 0, 0, 97, 5, 0, 0, 128, 104, 101, 108, 108, 111, 0, 0, 0, 0 };
byte[] output = new byte[255];
int read = LZ4Codec.Decode(input, 0, input.Length, output, 0, output.Length);
Console.WriteLine($"I read {read} bytes: {Encoding.ASCII.GetString(output)}");
```
and it gives the output:
`I read -1 bytes: "Mh@`

**Comment by MiloszKrajewski** [comment]
If lz4framed uses frame format (I guess it is) then `LZ4Codec.Decode` is NOT the right approach as it is for frame format (but you knew that). Anyway:

```
[Fact]
public void Issue27_DataPreparedWithPython()
{
	var raw = new byte[] {
		4, 34, 77, 24, 104, 64, 
		5, 0, 0, 0, 0, 0, 0, 0, 
		97, 5, 0, 0, 128, 104, 101, 
		108, 108, 111, 0, 0, 0, 0
	};
	using (var input = LZ4Stream.Decode(new MemoryStream(raw)))
	using (var reader = new StreamReader(input))
	{
		var text = reader.ReadLine();
		Assert.Equal("hello", text);
	}
}
```

It works.

**Comment by Jacobh2** [comment]
Thank you very much for the help here! Correct: I used the `LZ4Codec.Decode` wrong in the last post. Testing your provided code works as intended.

Doing some more testing shows me that I _do not_ seem to get the same byte array back from kafka as the one I put in. So I think it is something wrong with the kafka consumer settings where one of the bytes that should have value 128 gets value 63.

Thank you again for your time, I don't see that this is any issue with this lib, but instead issue at my end with kafka!

**Comment by Jacobh2** [comment]
Yes, correct! It was my settings with kafka that was messed up! Sorry for taking your time!
