### ISSUE TITLE
DecoderStream just reads first 65520 bytes

### ISSUE THREAD

**Issue by nexrom88** [MiloszKrajewski/K4os.Compression.LZ4#29]
hey there,

I have a strange problem by using the lz4decoder stream. It seems as if the decoder just decodes the first 65520 bytes. By reading further the decoder gives me random useless bytes. The underlying stream is a FileInputStream.
I created an own file format from which I read different sized byte blocks by using the LZ4Decoder Stream.

            //open base filestream
            FileStream sourceStream = new FileStream(System.IO.Path.Combine(this.path, file), FileMode.Open);

            //open decoder stream
            LZ4DecoderStream diffStream = LZ4Stream.Decode(sourceStream); 

            //read block count
            byte[] buffer = new byte[4];
            diffStream.Read(buffer, 0, 4);
            UInt32 blockCount = BitConverter.ToUInt32(buffer, 0);

            //iterate through all blocks
            for (int i = 0; i < blockCount; i++)
            {
                ulong offset;
                ulong length;

                //read block offset
                buffer = new byte[8];
                diffStream.Read(buffer, 0, 8);
                offset = BitConverter.ToUInt64(buffer, 0);

                //read block length
                int b = diffStream.Read(buffer, 0, 8);
                length = BitConverter.ToUInt64(buffer, 0);

                //read data block
                buffer = new byte[length];
                int a = diffStream.Read(buffer, 0, buffer.Length);

                //do sth with data block
            }
            diffStream.Close();

Now the first "for"- iterations work fine and after that "offset" and "length" vars contain strange incorrect values. As mentioned before that happens after I read 65520 bytes.
Before using your LZ4 implementation I used the .net built-in ZipArchive implementation. By using almost the same code as above the problem didn't exist.

What am I doing wrong or where is the problem here?
Thanks in advance.

**Comment by MiloszKrajewski** [comment]
I see nothing suspicious (apart from allocating buffer all the time). This is just a read part. Can you attach project which does both - writes data and reads data?

**Comment by nexrom88** [comment]
I think I found the problem.
I assumed that `diffStream.Read(buffer, 0, buffer.Length);` always reads "buffer.length" bytes from the stream. I found out that LZ4DecoderStream sometimes reads less bytes.

**Comment by UpUpLiu** [comment]
i have this problem too
i think you need give some info for this api to let other know this rule.

**Comment by nexrom88** [comment]
I think the problem is that DecoderStream buffers its decoded data internal within a 65536 bytes buffer. User first has to read all these bytes before this buffer gets filled again. That's when DecoderStream returns less bytes than needed.
I also tkink that this fact should get mentioned somewhere in the description of the API.

**Comment by MiloszKrajewski** [comment]
Well, it is documented in Stream API:
https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=netframework-4.8

```
Returns
Int32
The total number of bytes read into the buffer. This can be less than the number of bytes requested if that many bytes are not currently available, or zero (0) if the end of the stream has been reached.
```
