### ISSUE TITLE
Warnings in LZ4_Frame.cs

### ISSUE THREAD

**Issue by Krakean** [MiloszKrajewski/K4os.Compression.LZ4#3]
@MiloszKrajewski 
Hi. Suggest to add #pragma warning disable CS0169 in LZ4_Frame.cs to disable these warnings:
1>3rdParty\LZ4\Source\Internal\LZ4_Frame.cs(143,20,143,33): warning CS0169: The field 'LZ4_Frame.LZ4F_cctx_t.maxBufferSize' is never used
1>3rdParty\LZ4\Source\Internal\LZ4_Frame.cs(147,19,147,30): warning CS0169: The field 'LZ4_Frame.LZ4F_cctx_t.totalInSize' is never used
1>3rdParty\LZ4\Source\Internal\LZ4_Frame.cs(146,20,146,29): warning CS0169: The field 'LZ4_Frame.LZ4F_cctx_t.tmpInSize' is never used
1>3rdParty\LZ4\Source\Internal\LZ4_Frame.cs(144,19,144,26): warning CS0169: The field 'LZ4_Frame.LZ4F_cctx_t.tmpBuff' is never used
1>3rdParty\LZ4\Source\Internal\LZ4_Frame.cs(148,27,148,30): warning CS0169: The field 'LZ4_Frame.LZ4F_cctx_t.xxh' is never used
1>3rdParty\LZ4\Source\Internal\LZ4_Frame.cs(150,18,150,29): warning CS0169: The field 'LZ4_Frame.LZ4F_cctx_t.lz4CtxLevel' is never used
1>3rdParty\LZ4\Source\Internal\LZ4_Frame.cs(138,32,138,37): warning CS0169: The field 'LZ4_Frame.LZ4F_cctx_t.prefs' is never used
1>3rdParty\LZ4\Source\Internal\LZ4_Frame.cs(142,20,142,32): warning CS0169: The field 'LZ4_Frame.LZ4F_cctx_t.maxBlockSize' is never used
1>3rdParty\LZ4\Source\Internal\LZ4_Frame.cs(139,18,139,25): warning CS0169: The field 'LZ4_Frame.LZ4F_cctx_t.version' is never used
1>3rdParty\LZ4\Source\Internal\LZ4_Frame.cs(145,19,145,24): warning CS0169: The field 'LZ4_Frame.LZ4F_cctx_t.tmpIn' is never used
1>3rdParty\LZ4\Source\Internal\LZ4_Frame.cs(140,18,140,24): warning CS0169: The field 'LZ4_Frame.LZ4F_cctx_t.cStage' is never used
1>3rdParty\LZ4\Source\Internal\LZ4_Frame.cs(141,25,141,30): warning CS0169: The field 'LZ4_Frame.LZ4F_cctx_t.cdict' is never used
1>3rdParty\LZ4\Source\Internal\LZ4_Frame.cs(149,19,149,28): warning CS0169: The field 'LZ4_Frame.LZ4F_cctx_t.lz4CtxPtr' is never used

**Comment by MiloszKrajewski** [comment]
`LZ4_Frame` is not longer part of solution
