### ISSUE TITLE
Compression is not working

### ISSUE THREAD

**Issue by tdhung80** [MiloszKrajewski/K4os.Compression.LZ4#30]
Hi,

I have tried many tests, none of them is working.

`
var dataSize = 1000000;
var input = new byte[dataSize];
new Random().NextBytes(input);

var outputBuffer = new byte[LZ4Codec.MaximumOutputSize(input.Length)];
var bytes = LZ4Codec.Encode(input, 0, input.Length, outputBuffer, 0, outputBuffer.Length);
// bytes > 1000000 !!!?

outputBuffer = LZ4Pickler.Pickle(input);
// outputBuffer.Length > 1000000 !!!?

outputBuffer = LZ4Pickler.Unpickle(outputBuffer);
// outputBuffer.Length > 1000000 !!!?
`

My Bests,
Hung Tran

**Comment by MiloszKrajewski** [comment]
Well, "In particular, files of random data cannot be consistently compressed by any conceivable lossless data compression algorithm: indeed, this result is used to define the concept of randomness in algorithmic complexity theory."

https://en.wikipedia.org/wiki/Lossless_compression#Lossless_compression_techniques
