### ISSUE TITLE
Cannot use readasync

### ISSUE THREAD

**Issue by luyikk** [MiloszKrajewski/K4os.Compression.LZ4#35]
var lz4_input = LZ4Stream.Decode(input);

When I call  readasync, I can't call Inner stream readasync .

**Comment by MiloszKrajewski** [comment]
Yes, you are absolutely right.

If you take a look at https://github.com/MiloszKrajewski/K4os.Compression.LZ4/issues/5 you will find that "add true async read/write interface" is planned for vNext.

**Comment by luyikk** [comment]
thank, I'll make it myself [my](https://github.com/luyikk/LZ4Stream),  it works well. 
flush also needs make

**Comment by MiloszKrajewski** [comment]
Addressed in 1.2.5
