### ISSUE TITLE
Stream is not properly disposed

### ISSUE THREAD

**Issue by nerai** [MiloszKrajewski/K4os.Compression.LZ4#38]
Example:

	var path = "test.txt";
	var f = new FileStream (path, FileMode.Create, FileAccess.Write, FileShare.Read);
	var z = LZ4Stream.Encode (f);
	var w = new BinaryWriter (z, Encoding.UTF8, false);
	w.Write ("asdf");
	w.Dispose ();
	//z.Dispose ();
	File.Move ("test.txt", $"test2.txt");

results in IOException:

> The process cannot access the file because it is being used by another process.

Commenting in the `z.Dispose` solves the issue.

However, it should not be necessary due to the `leaveOpen: false` parameter.

Note: Using `Close` instead of `Dispose` on `z` does NOT work. It seems `BinaryWriter` calls `Close` on its base stream, expecting it to be equivalent to `Dispose`. But that seems to not be the case for LZ4Stream.

**Comment by MiloszKrajewski** [comment]
I looks like you are right.
Actually, I'm surprised that `BinaryWriter.Dispose()` does not call `Stream.Dispose()` (just `Close()`). It is a little bit counter intuitive.

Although, according to documentation `Close()` should dispose stream, so my implementation of Close is a little but off.

**Comment by MiloszKrajewski** [comment]
Addressed in 1.2.5
