### ISSUE TITLE
xxhash dependency

### ISSUE THREAD

**Issue by Krakean** [MiloszKrajewski/K4os.Compression.LZ4#4]
@MiloszKrajewski 
Curious, what is it for?
And, can it be done via some common interface instead of lock-in to xxHash? 
Like a IHasher with doHash() function or something like this, so I can provide my own hash library that I use to do the required hash job?
For example, in my game engine I prefer FarmHash (https://github.com/nickbabcock/Farmhash.Sharp this port particullary, which seems faster to me) instead of xxHash.

**Comment by Krakean** [comment]
@MiloszKrajewski curious, is project alive?

**Comment by MiloszKrajewski** [comment]
Skiing holiday :-)

**Comment by Krakean** [comment]
@MiloszKrajewski oh :) when you plan back to lz4?

**Comment by Krakean** [comment]
@MiloszKrajewski ping :)

**Comment by MiloszKrajewski** [comment]
working :-) stream decoder is now decompressing streams created with lz4.exe (reference implementation)

**Comment by MiloszKrajewski** [comment]
BTW, for now I'm not checking any hash at all. I'm just ignoring it, so them whole discussion might be a little bit premature. Although, my primary goal is 100% compatibility, so xxhash with be definitely default option, and only option in version 1.0.
Plugable hashing algorithm sounds cool but it is not priority. NOTE: The only required hash is a hash of ~16 bytes of header, no block not content hashes are required.

**Comment by MiloszKrajewski** [comment]
Moved to ticked called '1.0.0-alpha'

**Comment by Krakean** [comment]
@MiloszKrajewski 
> whole discussion might be a little bit premature.

Think that things like this better to discuss while development in alpha :)

>Plugable hashing algorithm sounds cool but it is not priority.

Just in my opinion it wouldn't be so hard to implement via somekind of interface I suggested, so would be nice if v1.0 have it.
Plus, in my case for example I have no intention to have compatibility with any official reference implementation (in case if xxhash is matters in context of compability), because I use your library in my game engine for assets archive format, so would be nice for me as lib user to provide my own hash function :)
