### ISSUE TITLE
OverflowException: Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by mjebrahimi** [MiloszKrajewski/K4os.Compression.LZ4#42]
**Description**
I found that for large file sizes this exception occurs on decompressing in a period of 8 megabytes!
For example between files with actual size (before compress) is between 1 to 8 MB, decompress works but for files with actual size between 9 to 16 MB, that exception occurs on decompressing. also for 17 to 24 MB is OK and for 25 to 32 is not OK and so on...

**To reproduce**
Check out this [sample](https://dotnetfiddle.net/92D58J).

**Comment by MiloszKrajewski** [comment]
Your test is throwing the exception not compression. Array (length * 255) is too large.
