### ISSUE TITLE
[Solved] System.TypeInitializationException starting from 1.2.5

### ISSUE THREAD

**Issue by jensd0e** [MiloszKrajewski/K4os.Compression.LZ4#44]
Hi,

Starting from version 1.2.5, using LZ4Pickler.Pickle(), I get a System.TypeInitializationException. Downgrading to 1.1.11 fixes this.

var compressed = LZ4Pickler.Pickle(source);

Exception: The type initializer for 'K4os.Compression.LZ4.Engine.LL' threw an exception.
Inner Exception: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.6.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

I'm clueless, how to fix this. Searching the net, it's seems to be a binding issue. But the proposed solution(s) didn't work for me. Or I just failed to apply them the right way. ;-)

.NET: 4.7.2 Framework
LZ4: 1.2.X

**Comment by MiloszKrajewski** [comment]
Cannot reproduce. Can you zip some example project with this problem?

**Comment by MiloszKrajewski** [comment]
You can try: 1.2.8-beta. I've changed nothing but now System.Runtime.CompilerServices.Unsafe is referenced implicitly.

**Comment by jensd0e** [comment]
1.2.8-beta doesn't work either. Same error. 

I'll prepare some code to figure out, if this happens only within this project or with any project (on my machine). Will be reporting back here. Thanks for your support. :-)

**Comment by jensd0e** [comment]
Didn't find anything making sense. :-( 
In a fresh project, the library is working as expected. The problem seems to be somewhere hidden deep inside in my Solution.
 
What makes this worse: 1.2.2-beta is the last working version. It started to throw the exception beginning with 1.2.4-alpha. Diffing those two versions, I could not spot anything, that could possibly be related. Actually just an added file (issue-template.txt) and a changed README.md.

So, if anybody has a clue, about what's wrong with my Solution, please let me know.

**Comment by MiloszKrajewski** [comment]
I would suggest refreshing nuget packages and checking app.config for redirections. It seems like it is not pull System.Runtime.CompilerServices.Unsafe into packages folder.

**Comment by jensd0e** [comment]
Among other things, I tried cleaning my solution. I Manually removed everything inside the package folder and let VS restore the content. I even did a comparision of my whole solution. Besides some (own) DLLs and binaries, only two files where different: my *.csproj and the packages.config. And both only showed a change in version numbers. No change in path or folders. 
Something is broken with this project/solution. After I've done some other work, I'll try to solve this riddle and report back.
