### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by DotNetCoder82** [MiloszKrajewski/K4os.Compression.LZ4#45]
**Description**
I downloaded LZ4 project, however, as stated in instructions, I am unable to build and receiving attached error.

I have .NET Core SDKs installed.

**To reproduce**
Download package and run paket restore on command prompt

**Expected behavior**
I expected build would proceed normally as stated in instructions.

**Actual behavior**
A clear and concise description of what actually happens.

**Environment**
 - CPU: Intel 64-bit
 - OS: Windows 10
 - .NET: .NET Core 2.1.519
 - LZ4: 1.2.8-beta
![LZ4_Build_Error](https://user-images.githubusercontent.com/65447938/97263685-85b76500-1849-11eb-9136-740572c1e9d3.JPG)

**Additional context**

**Comment by MiloszKrajewski** [comment]
Command which fails is:
`dotnet tool install paket --tool-path .paket`
can you run this is LZ4 folder?
The other thing is .NET Core SDK 2.1... I wasn't using 2.1 for very long time, Try 3.1?

**Comment by DotNetCoder82** [comment]
Above command failing on 3.1 SDK as well:

![image](https://user-images.githubusercontent.com/65447938/97295971-05f3bf80-1876-11eb-82ad-e238d6400d63.png)

**Comment by MiloszKrajewski** [comment]
I honestly have no idea.
3.1.403 won't work for [different reason](https://github.com/fsprojects/Paket/issues/3897), but what I see is perplexing.

What it tries to do is to download 'paket' from nuget. For some reason it decides to not download it (or is not finding it) and tries to find it in local cache. The fact that you don't have it in local cache cache is understandable, but I have no idea why it does not download it.

Can you try to download other dotnet tool in this folder?

**Comment by MiloszKrajewski** [comment]
Wait a sec, it seems like you are doing it as system administrator. This might also be a factor (different cache location?). Try as regular user.

**Comment by DotNetCoder82** [comment]
Attached files are missing in .paket folder.
![image](https://user-images.githubusercontent.com/65447938/97429488-7e718380-193d-11eb-9b93-2c673180a330.png)

Also, .NET 4.6.2 SDK is required to build.

**Comment by MiloszKrajewski** [comment]
They are no missing, they get redownloaded, and for some reason they ar not on your machine:

![image](https://user-images.githubusercontent.com/4333436/97457376-99d69180-1931-11eb-861c-85338e580c26.png)

**Comment by MiloszKrajewski** [comment]
Let me know if this is still a problem.
