### ISSUE TITLE
XA3001: Cannot AOT the assembly: K4os.Compression.LZ4.dll

### ISSUE THREAD

**Issue by ryancheung** [MiloszKrajewski/K4os.Compression.LZ4#46]
**Description**
I got this error when compile Xamarin.Android app with llvm & AOT enabled:
```xml
    <AotAssemblies>true</AotAssemblies>
    <EnableLLVM>true</EnableLLVM>
```

**To reproduce**
Just compile a Xamarin.Android project with llvm and AOT enabled.

**Expected behavior**
Should be able to AOT

**Actual behavior**
XA3001: Cannot AOT the assembly: K4os.Compression.LZ4.dll

**Environment**
 - CPU:  Intel 64 bit
 - OS: Windows
 - .NET: Xamarin
 - LZ4: 1.2.6

**Additional context**

**Comment by MiloszKrajewski** [comment]
I would suggest raising it with AOT compiler. These people would know how to read compiler logs and diagnostic messages.

**Comment by ryancheung** [comment]
Just noticed that llvm AOT is experimental feature. I should consider this a mono aot issue. Thanks for response anyway.
