### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by NiclasOlofsson** [MiloszKrajewski/K4os.Compression.LZ4#49]
Sorry for the spam, but really just wanted to leave a comment to tell you how much I appreciate this lib. I managed to compress my bit-stream of images up to 95% at virtually no cost. It's insane. I wouldn't believe it if I didn't see the images on the other side of the wire.

**Comment by MiloszKrajewski** [comment]
Thank you for your kind words!

I can take credit for porting and making .NET interface around it, but performance, well... you should give credit when credit is due: @Cyan4973 and whole [LZ4](https://github.com/lz4/lz4) team!
