### ISSUE TITLE
Can't Build. Restore:Corpus  Execution failed with error code 2

### ISSUE THREAD

**Issue by bluedoom** [MiloszKrajewski/K4os.Compression.LZ4#56]
D:\C#Projects\K4os.Compression.LZ4>fake build
![image](https://user-images.githubusercontent.com/29087010/108581901-03f4c580-736b-11eb-98f4-e55d4b1caef7.png)

**Comment by MiloszKrajewski** [comment]
Can I have full log, please. I think the answer to "what actually failed?" is on previous pages unfortunately.

**Comment by bluedoom** [comment]
> Can I have full log, please. I think the answer to "what actually failed?" is on previous pages unfortunately.
Thanks for your reply!  I got this : 
Processing archive: .\.corpus\nci.zip
Error: Can not open file as archive
I delete the nci.zip(which is 0 size) , and re-download it.
