### ISSUE TITLE
Decode with endOnOutputSize

### ISSUE THREAD

**Issue by gibbed** [MiloszKrajewski/K4os.Compression.LZ4#61]
It doesn't appear that decoding with `endOnOutputSize` is exposed. Is there any plan to make this available?

I'm after partial decoding of data, where I know the uncompressed and compressed sizes, but would like to do partial decoding to get at a file header before I choose to decode the entire file. Currently if I try to do this with `LZ4Codec.Decode` it returns `-1` without any bytes written to my output buffer.

The relevant underlying C# implementation is all set to `internal`, so I can't just readily use that without making my own build of this library, I think.

**Comment by MiloszKrajewski** [comment]
Release in `[v1.3.7-beta](https://github.com/MiloszKrajewski/K4os.Compression.LZ4/releases/tag/1.3.7-beta)` (see #90)
