### ISSUE TITLE
Dependency to System.Memory  is not needed for .NET Standard 2.1 and .NET 5.0

### ISSUE THREAD

**Issue by tibel** [MiloszKrajewski/K4os.Compression.LZ4#63]
In newer frameworks (.NET Standard 2.1 and .NET 5.0) `Span` is supported out of the box and the NuGet package is not needed.

**Comment by redwyre** [comment]
This is something I am very interested in as well as the extra references cause issues with Unity

**Comment by MiloszKrajewski** [comment]
1.2.16 should do exactly this

**Comment by redwyre** [comment]
Thanks @MiloszKrajewski! Are you able to make the same change in https://github.com/MiloszKrajewski/K4os.Hash.xxHash ?

**Comment by MiloszKrajewski** [comment]
@redwyre xxHash 1.0.7 has same changes applied. 
Note LZ4 still references 1.0.6 so you need to manually reference xxHash 1.0.7.
I'll change it in next release.
