### ISSUE TITLE
excuse me, it work to Unity Engine?

### ISSUE THREAD

**Issue by qcbf** [MiloszKrajewski/K4os.Compression.LZ4#66]
"1.2.16 Source code"  copy to Unity,  i get many error. what did i miss. 
thank  very much
![Snipaste_2021-12-27_16-51-20](https://user-images.githubusercontent.com/3467543/147454081-54c8f802-db9e-48e6-9543-f2e722e1f157.png)

**Comment by MiloszKrajewski** [comment]
It should, but I don't know because I'm not using Unity - but it promises to be compatible with .NET Standard.
Maybe @redwyre can help?

**Comment by redwyre** [comment]
Sure, if you're using Unity 2020 or earlier it is only compatible with .net standard 2.0. You will need to copy the other dependencies like System.Memory, but downloading from nuget and adding to your Unity Project.

An easier way to make this work would be to a dummy library project (netstandard2.0) and add the nuget references for K4os.Compression.LZ4 and System.Memory, then just copy everything in the output directory to your Unity Project. No need to compile from source.

**Comment by qcbf** [comment]
> "1.2.16 Source code" copy to Unity, i get many error. what did i miss. thank very much ![Snipaste_2021-12-27_16-51-20](https://user-images.githubusercontent.com/3467543/147454081-54c8f802-db9e-48e6-9543-f2e722e1f157.png)

thank everyone
