### ISSUE TITLE
How to uncompress an LZ4 archive that has multiple files?

### ISSUE THREAD

**Issue by Razique** [MiloszKrajewski/K4os.Compression.LZ4#68]
**Description**
Hi,
I have created an `.lz4` archive that contains files and folders using `tar`:
```
tar --use-compress-program=lz4 -cf Archive.tar.lz4 output
```

And I am running the current code to create a file stream:
``` csharp
using (var source = LZ4Stream.Decode(stream: File.OpenRead(ArchiveSrcPath), leaveOpen: true))
using (var target = File.Create(@$"{ArchiveDstPath}"))
{
    source.CopyToAsync(target);
}
```
It seems to me that I need to perhaps find ways to iterate over all files within the archive, but I couldn't find anything in the documentation that explains which method could have an iterator.

thanks!

**To reproduce**
```
StringBuilder sb = null;
sb.Append("BANG!");
```

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Environment**
 - CPU: _ [Intel, ARM, Samsung, 32/64 bit]
 - OS: _ [Windows, MacOS, Android]
 - .NET: _ [Version, Framework, Core, Mono, Unity, Xamarin]
 - LZ4: _ [Version, Alpha/Beta]

**Additional context**

**Comment by MiloszKrajewski** [comment]
There is only one file inside LZ4 archive, always.
The (only) file inside LZ4 archive is a TAR file.
It is the TAR file which contains many files.

So, you need a library which deal with TAR files, for example: [SharpZipLib](https://github.com/icsharpcode/SharpZipLib).

When you have it you can just nest streams:

```csharp
private static void UntarMany(string sourceName)
{
	using var sourceFile = File.OpenRead(sourceName);
	using var lz4File = LZ4Stream.Decode(sourceFile);
	using var tarFile = new TarInputStream(lz4File, Encoding.UTF8);

	while (true)
	{
		var entry = tarFile.GetNextEntry();
		if (entry is null) break;
		
		using var targetFile = File.Create(Guid.NewGuid().ToString());
		
		CopyEntry(tarFile, targetFile, (int) entry.Size);
	}
}

private static int CopyEntry(Stream sourceFile, Stream targetFile, int partSize)
{
	var buffer = new byte[4096];
	var copied = 0;
	while (partSize > 0)
	{
		var chunkSize = Math.Min(buffer.Length, partSize);
		var read = sourceFile.Read(buffer, 0, chunkSize);
		if (read == 0) break;

		targetFile.Write(buffer, 0, read);
		partSize -= read;
		copied += read;
	}
	return copied;
}
```

Example is [here](https://github.com/MiloszKrajewski/K4os.Compression.LZ4/blob/62ca61d93c9864b90acbc722f29e06e53dcd5c4d/src/K4os.Compression.LZ4.Streams.Test/TarTests.cs#L67)

**Comment by Razique** [comment]
Thank you so much @MiloszKrajewski. It worked like a charm. This code allowed me to reach near native speed when unarchiving my tar.
It is worth pointing an interesting issue for those who stumble on this thread: `tar` operations on Windows are pretty slow, unless Windows Defender is disabled. This is visible when you are dealing with a large data set.
[More information here](https://github.com/microsoft/Windows-Dev-Performance/issues/27)
