### ISSUE TITLE
LZ4Codec.Decode returns -1 instead of correct length

### ISSUE THREAD

**Issue by ZunTzu** [MiloszKrajewski/K4os.Compression.LZ4#7]
Hi, Milosz!
I hope reporting this issue will be helpful. Here is a source code example which exhibits the issue:

            string text = "The quick brown fox jumps over the lazy dog";
            byte[] textBytes = System.Text.Encoding.UTF8.GetBytes(text);

            byte[] encoded = new byte[LZ4Codec.MaximumOutputSize(textBytes.Length)];
            int encodedLength = LZ4Codec.Encode(
                textBytes, 0, textBytes.Length,
                encoded, 0, encoded.Length);

            byte[] decoded = new byte[textBytes.Length * 2];
            var decodedLength = LZ4Codec.Decode(
                encoded, 0, encoded.Length,
                decoded, 0, decoded.Length);

            Assert.Equal(textBytes.Length, decodedLength); // -1 instead of 43

**Comment by MiloszKrajewski** [comment]
Just change:

```
var decodedLength = LZ4Codec.Decode(
            encoded, 0, encoded.Length,
            decoded, 0, decoded.Length);
```

to:

```
var decodedLength = LZ4Codec.Decode(
            encoded, 0, encodedLength,
            decoded, 0, decoded.Length);
```

Very well hidden :-)

**Comment by ZunTzu** [comment]
Thanks a lot!
