### ISSUE TITLE
[Feature]: .NET 6 target and assembly trimming

### ISSUE THREAD

**Issue by ds5678** [MiloszKrajewski/K4os.Compression.LZ4#70]
It would be nice to have a .NET 6 target that supports [trimming](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming).

I tried to do this myself based on 15007a81a20addd6b50d29f74d3cbce25593df74, but `paket.lock` is an unreadable mess.

**Comment by MiloszKrajewski** [comment]
Make sense. I will take a look. 
In general `paket.lock` is not a file you modify manually, so its readability has secondary importance.

**Comment by MiloszKrajewski** [comment]
.NET 6 release in [1.3.0-beta](https://github.com/MiloszKrajewski/K4os.Compression.LZ4/releases/tag/1.3.0-beta)

**Comment by ds5678** [comment]
Much appreciated
