### ISSUE TITLE
Unity Support

### ISSUE THREAD

**Issue by DoktorAce** [MiloszKrajewski/K4os.Compression.LZ4#71]
Unity is mentioned under the very last section in the readme. But things like `ReadOnlySpan` from `System.Memory.dll` requires .net 5+ which Unity does not support? Or am I missing something here, because I can't get it to compile in Unity 2020.2.

**Comment by MiloszKrajewski** [comment]
I am not using Unity myself, so I don't know, but people did use it with Unity.

The other of your statements is actually not true: `System.Memory` is compatible with:
(source: https://www.nuget.org/packages/System.Memory/4.5.4)
```
.NETCoreApp 2.0
.NETCoreApp 2.1
.NETFramework 4.5
.NETFramework 4.6.1
.NETStandard 1.1
.NETStandard 2.0
MonoAndroid 1.0
MonoTouch 1.0
Portable Class Library (.NETFramework 4.5, Windows 8.0, WindowsPhoneApp 8.1)
UAP 10.0.16299
Windows 8.0
WindowsPhoneApp 8.1
Xamarin.iOS 1.0
Xamarin.Mac 2.0
Xamarin.TVOS 1.0
Xamarin.WatchOS 1.0
```
So, it SHOULD work without a problem. If it doesn't (which is possible) it is for a DIFFERENT reason.

**Comment by MiloszKrajewski** [comment]
You may take a look at #66

**Comment by MiloszKrajewski** [comment]
Did you make it work?
