### ISSUE TITLE
Question about random access, i want to make something similar to the original dictionaryRandoimAccess.c example

### ISSUE THREAD

**Issue by GamingCity** [MiloszKrajewski/K4os.Compression.LZ4#81]
Hi,
this is not a bug report, i want to ask about this. I have a working random access implementation in C/C++ using the original lz4 lib, i want to bring this into .NET and i belive this lib is my best bet.

So this is the example i was talking about: 
https://github.com/lz4/lz4/blob/dev/examples/dictionaryRandomAccess.c

In this lz4 example the file structure produced i belive it is non standart:
header magic | N Blocks |jump table N entries|number of blocks/entries in jump table

And the implementation i did in C++ i added additional data at the end, the original file size and the block size so all files had all data i needed to decompress them. So in my case is more like this:
header magic | N Blocks |jump table N entries|number of blocks/entries in jump table|original filesize|blocksize

The only difference is that im not using a dictionary, and instead i just reset the stream at every block to make them independient.
This is working really well as i can read any N bytes at any X position of the original file whiout having to decompress the entire chain leading up to that point.

Now i want to make a compressor and decompressor in .net that can produce and read that same format, i dont really need to random access the files here, just produce them and also being able to extract them.

Can someone point me in the right direction of were i just start looking in this lib in order to implement that? i think i can do it if i get some guidance.

Thank you.

**Comment by MiloszKrajewski** [comment]
I'm not sure I grasp what code you mentioned really does and how it does it, but I do have some thoughts:

* initial block sizes are known, so when you seek you can quickly skip blocks without decompressing them
* ...unless they are chained / dependent blocks

So Seek / Read is kind of possible with caveats:
* independent blocks only
* skip blocks without decompression
* decompress whole block containing bytes you need

**Comment by MiloszKrajewski** [comment]
To plug `Seek` into stream you would need to start somewhere in [LZ4FrameReader.vs](https://github.com/MiloszKrajewski/K4os.Compression.LZ4/blob/master/src/K4os.Compression.LZ4.Streams/Frames/LZ4FrameReader.async.cs) but then a lot of work would be in [LZ4BlockDecoder.cs](https://github.com/MiloszKrajewski/K4os.Compression.LZ4/blob/master/src/K4os.Compression.LZ4/Encoders/LZ4BlockDecoder.cs).

This is kind of doable but all abstractions are built with no Seek in mind at all, see:
[IStreamReader.cs](https://github.com/MiloszKrajewski/K4os.Compression.LZ4/blob/master/src/K4os.Compression.LZ4.Streams/Abstractions/IStreamReader.cs)

**Comment by GamingCity** [comment]
Just a little clarification, i dont really need to seek the compressed stream in the lib, altrought that will be nice to have too and i may look into that too. Im looking to make a .net compressor/decompressor program that can produce the files in this format, the decompress process in the lib should be done normally (the entire file from start to finish). A open source C++ game called Freespace Open is the one that will read and use those files using random access.

You are right about the block sizes and their position on the stream, a offset table should not be needed, thats a good point, i made that implementation over two years ago and im reading back what i did and i cant understand it either, i mostly followed the official example, maybe im missing something, but it really seems to contain the block position in the stream.

If im correct, if i create a stream right now, with independient blocks, it will have the lz4 frame format https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md?

First i want to produce a file with the structure i used following the random access example + the two extra ints as thats is the structure that the game uses, then i want to see if i can make work with the lz4 frame format, if this is possible i can look into adding the seeks here too.

Do you think is possible to change the output format to the one i need? (im not looking to PR that, just to use it for this expecific implementation).

**Comment by Shivansps** [comment]
Hi, i just re-checked the C code i did 2 years ago, it works like this:
Since each block contains BLOCK_SIZE of uncompressed data, except maybe the last, the trailing offset table contains the seek position of each block in the stream, and the position you are looking for % BLOCK_SIZE gives the block number were that data is.

Not sure if this can be donde whiout the offset table what makes it incompatible with the lz4 frame format i belive? If it can be done with the lz4 frame format it would be also be great to know because i can certanly change the game to accept that too.

But if you can at least help me to point me to were i need to look in order to change the format in order to produce something like this i would be very grateful. 

Thank you.

**Comment by Shivansps** [comment]
Hi, sorry, in the end i found another lib were i was able to add what i needed very quickly. Thanks for you help anyway. You can close this.
