### ISSUE TITLE
Strongly named assembly

### ISSUE THREAD

**Issue by juanyaw** [MiloszKrajewski/K4os.Compression.LZ4#9]
Hi Milosz, can your assemblies be strongly named once again like the old lz4net version was?

**Comment by MiloszKrajewski** [comment]
I quite reluctant to do it. It's a pain when you have dependencies depending on different versions. 
I'm looking now at public signing (https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/public-signing.md) maybe this will solve the problem.

**Comment by MiloszKrajewski** [comment]
New version should be strongly signed now.
Although it also has some breaking changes (if you use pubternals).
https://www.nuget.org/packages/K4os.Compression.LZ4/1.1.0
