### ISSUE TITLE
[Question] Block vs Stream vs Pickler to store compressed bitmaps in memory

### ISSUE THREAD

**Issue by sn4k3** [MiloszKrajewski/K4os.Compression.LZ4#94]
I currently use LZ4 block to de/compress bitmaps and store them in memory. Every time a bitmap is used it is decompressed. If is modified, then it's compressed to memory. 
Performance it's very good but the unknown size of compress data makes large allocations. To "solve" that I'm using `ArrayPool`, however images are growing in size and I don't know if `ArrayPool` can handle such large arrays.

To give a better understanding of the scope, my app is [UVtools](https://github.com/sn4k3/UVtools):
![image](https://github.com/MiloszKrajewski/K4os.Compression.LZ4/assets/113281/b47f0094-4192-482d-812f-0268c169c3a1)

- It opens a file which contain a stack of layers. 
- All layers are simple 8 bit bitmaps and with same resolution.
- For example on the screenshot above, the file contains 1001 images with 4k resolution.
- Decompress size is always known (X * Y) 

However some files are starting to have 12k resolution images, and there are files with 2000 or more layers. Again, not a problem, but I'm seeking advice of which method I should use better to relief the memory allocation in compress time.

On screenshot you can notice that 1001 image compressions were made under 1s (Program first decode image in its original format eg png, then compress to store all in memory) and the instance is using 586MB ram for whole program which is great.

Currently using these methods:

```C#
private byte[] _compressedBytes = Array.Empty<byte>();

//
// To decompress
//
mat = new Mat(Resolution, DepthType.Cv8U, 1);
LZ4Codec.Decode(_compressedBytes.AsSpan(), mat.GetDataByteSpan());

//
// To compress
//
var span = mat.GetDataByteSpan();

// Large allocations! eg: 12288 * 6480 + (extra from MaximumOutputSize)
var rent = ArrayPool<byte>.Shared.Rent(LZ4Codec.MaximumOutputSize(span.Length));
var rentSpan = rent.AsSpan();

var encodedLength = LZ4Codec.Encode(span, rentSpan);
_compressedBytes = rentSpan[..encodedLength].ToArray();

ArrayPool<byte>.Shared.Return(rent);
```

So is there any tweak or better process I can use to relief the heap allocations without negatively impact performance?
The more CPU core count the more parallel compressions are made, in my case 32 cores generate a ton of allocation.

**Comment by MiloszKrajewski** [comment]
Rule number one of performance is: Measure!

I don't know what is bigger pain, memory allocation or large objects, or a little bit of pressure from small object.
Both BLOCK and Pickler need to allocate whole output buffer, so both will have same problem. Pickler is just BLOCK but a little but simpler to use if you don't want to get into details.

If you have a suspicion that most of the time images compress well, so those allocations are actually quite wasteful, you should try STREAM. It will definitely help with LOH allocation but for a price of some extra copying. Check out `LZ4Frame` class and use some `Stream` in memory. I say `Stream` in memory not `MemoryStream` because `MemoryStream` has horrible performance, but try `https://github.com/MiloszKrajewski/K4os.Streams` especially `ChunkedByteBufferStream`.

Let me know if it helps.

**Comment by sn4k3** [comment]
Thanks, I will have a look and do some testing. At first sight if I want to use `ChunkedByteBufferStream` with `LZ4Frame` I need to implement own IBufferWriter around `ChunkedByteBufferStream`, correct?

**Comment by MiloszKrajewski** [comment]
> Thanks, I will have a look and do some testing. At first sight if I want to use `ChunkedByteBufferStream` with `LZ4Frame` I need to implement own IBufferWriter around `ChunkedByteBufferStream`, correct?

Well, no - and yes.

I was thinking that you could use it as a `Stream` (not as `IBufferWriter<byte>`), and keep it as such stream, never actually allocating contiguous blocks of memory. 

`ArrayByteBuffer<byte>` is allocating one block of memory, expanding it if it is needed. So it has a problem of reallocation, but at the same time, maybe if you streams compress well it is not really a problem, as it will not happen a lot.

Your options are:
* use STREAM protocol with `ChunkedByteBufferStream` (which is a stream) (con: `Stream` related overhead)
* use STREAM protocal with `ArrayByteBuffer<byte>` (con: realocation)

Third, but also quite complex option would be to wrap [ChunkedByteBufferStream](https://github.com/MiloszKrajewski/K4os.Streams/blob/main/src/K4os.Streams/Buffers/ChunkedByteBuffer.cs ) in some adapter implementing `IBufferWriter<byte>`, but I think you will find out some serious incompatibilities (related to `GetSpan(...)` requirement to assure returned block in contiguous).



I would definitely try 1 and 2.

**Comment by sn4k3** [comment]
To ease things, I tried with [SparseBufferWriter](https://sakno.github.io/dotNext/features/io/buffers.html) as it can pass directly to your LZ4Frame, however performance is a bit worse.

```C#
var span = mat.GetDataByteSpan();
using var buffer = new SparseBufferWriter<byte>(span.Length / 100);
LZ4Frame.Encode(span, buffer, LZ4Level.L00_FAST);
var result = new byte[buffer.WrittenCount];
buffer.CopyTo(result);
return result;
```

Here the result using my benchmark tool from the application itself:

![image](https://github.com/MiloszKrajewski/K4os.Compression.LZ4/assets/113281/318a6077-6d80-4bd2-9355-a9f06eb3d75b)
45% worse in multi-thread over 5000 compressions in 4K


I will continue making some tests and compare

**Comment by MiloszKrajewski** [comment]
Seems like streaming overhead is too much. What about another gamble:

Purposely allocate less memory and gamble. Compression may fail in such case so you will need to rerun it with full buffer in such case.
* PRO: potential gain in optimistic scenarios
* CON: twice as slow in pessimistic case

**Comment by sn4k3** [comment]
> Purposely allocate less memory and gamble. Compression may fail in such case so you will need to rerun it with full buffer in such case.

I thought about that, but I not yet find a good ratio. Without extra processing I have the bounding area and positive pixels. However compressed size can vary with the pattern of the pixels. 
I may end in just store the bounding area instead of whole bitmap. For example on a 12k image if just 100x100 is used I may store only that at a cost of a crop.

Example of a bounding area in a 12K image:
![image](https://github.com/MiloszKrajewski/K4os.Compression.LZ4/assets/113281/01744be1-ee2c-4c8b-95a4-3088e1b4d0fc)

> This is is kind of what pickler does: it does not allocate MaxOutputSize(sourceLength) just sourceLength, so when it fail we now that it cannot be compressed, so raw copy is enough.

In real scenarios I never expect buffers near sourceLength, I only saw >sourceLength when using non-sense images like a full random noise bitmap generated by code...

Before ArrayPool I use normal array, VS complain about huge allocations, I turn over ArrayPool but I always suspect that would not help much because this information:

> ArrayPool of int type for simplicity purposes. The defaultArrayPool is a shared instance that can handle managed ready-to-use arrays of integer type. This pool has a default max array length, equal to 2^20 ( 1024*1024 = 1.048. 576 ) bytes

Even a fullhd image pass that limitation however when I start using ArrayPool the compression performance increased by a good margin, so it's doing something, however 32 rents of 12k look insane to me and I wonder how it works in first place.

___

Anyway, your library is awesome! I also include other compressors and user can opt, but LZ4 prove to be the best.
Here the chart:

![image](https://github.com/MiloszKrajewski/K4os.Compression.LZ4/assets/113281/0af292f8-1846-41b6-a16b-6523ebab2222)

The deflate and gzip is using MemoryStream...

**Comment by sn4k3** [comment]
I end in compress only the usable area of the image and that show's superior performance gain and less memory footprint in both compress/decompress time. I also set an threshold for it start to compress, eg: very small arrays don't need to compress. 

Memory results:
![image](https://github.com/MiloszKrajewski/K4os.Compression.LZ4/assets/113281/7c9129a2-f2e4-44a0-9206-52e5ffa45067)

My implementation: https://github.com/sn4k3/UVtools/blob/master/UVtools.Core/EmguCV/CMat.cs

**Comment by MiloszKrajewski** [comment]
This does not look right: https://github.com/sn4k3/UVtools/blob/2d542b02f451fac98ab23e3995820d176cd099a0/UVtools.Core/EmguCV/CMat.cs#L583

First, hash code should depend only on things which are fast to calculate (if you really need array, take 16 first and 16 last bytes, for example), but also can depend on immutable properties only.

```
class A { public int X; int GetHashCode() => X; }

var a = new A() { X = 42; }
var s = new HashSet<A>();
var l = new List<A>();

s.Add(a);
l.Add(a);

l.Contains(a); // true
s.Contains(a); // true

a.X = 1337;

l.Contains(a); // still true
s.Contains(a); // false !!!
```

**Comment by sn4k3** [comment]
I admit that I use the default template when overriding `Equals` that brings all that GetHashCode.
I understand that the hash code should be fast and use only immutable fields. However, nothing on this class is immutable. 
Even if I never expect to use this class on a Hash style I know it still a bad design.

I think I will just replace the GetHashCode with: `return RuntimeHelpers.GetHashCode(this);` so it returns the hashcode from instance pointer. What you think?

**Comment by MiloszKrajewski** [comment]
This is an option, and I think it is better.
Problem with previous solution is that object cannot find itself:

```csharp
s.Add(a);
a.V = 1337;
s.Contains(a); // false - what the hell?
```

The solution with `RuntimeHelpers.GetHashCode(this)` (which is default implementation) at least guarantees that:

```csharp
s.Add(a);
a.V = 1337;
s.Containts(a); // true - it is still there
```

it definitely does not guarantee similar objects to be found:

```csharp
s.Add(a);
a.V = 1337;
b.V = 1337;
s.Contains(a); // true - it is still there
s.Contains(b); // false - b is technically a different object than a, even if they "look" the same
```
