### ISSUE TITLE
Adding non compressed data at the end of the stream

### ISSUE THREAD

**Issue by julienlesur** [MiloszKrajewski/K4os.Compression.LZ4#95]
Hi,
First, I'd like to congrat you and thank you for this great library.

In a current project, I need to create a stream with non compressed data at the beginning, and the end but compressed data in the middle (several blocks if possible).
I easily could write non compressed data followed by compressed data and read it. But I can't find any solution to add non compressed data at the end.

Here is one of the many failing ways I tried, could you give me a hint?

`
            //First stream
            using var streamHeader = WriteMindVersionSection();
            //Second stream
            using var streamModelInformations = WriteModelInformations(globalModel, modelIndex, instanceIndex, isInterlinkExtraction, out var gridIndicesToSave);
            streamModelInformations.Seek(0, SeekOrigin.Begin);
            
            using var compressor = LZ4Stream.Encode(streamHeader);
            //Compressing the stream and adding it to streamHeader
            streamModelInformations.CopyTo(compressor);

            //Then one the many ways I try to add non compressed at the end, Fails like the rest
            using var streamPositionSection = new MemoryTributary();
            using var bwPosition = new BinaryWriter(streamHeader);
            bwPosition.Write((short)14);
            bwPosition.Write(21l);
            bwPosition.Write(100000l);

            return streamHeader;`

I can after read values that were at the beginning of streamHeader and the compressed values in streamModelInformations but if I try to go directly before the short and the two long at the end of the stream, the values I obtain are different than the one I initially wrote.
Thanks for advance if you can help me (and even if you can't ;) )

**Comment by julienlesur** [comment]
The problem was finally resolved, in each method that are building a part stream, I "force" the compressor to be disposed at the end of the method instead of letting the garbage collector do it by its own.

Sorry for the stupid question and thanks once again for your great library

**Comment by MiloszKrajewski** [comment]
Not sure if what you did is right.

What you need, is to `Dispose` LZ4 stream, but not underlying Stream. You can use `leaveOpen` argument for that:

https://github.com/MiloszKrajewski/K4os.Compression.LZ4/blob/52f43450287e0626276e72ac9cb483dca73bfeac/src/K4os.Compression.LZ4.Streams/LZ4Stream.cs#L16
